name: Check

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always
  COLUMNS: 80
  LINES: 24

jobs:
  dev-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: swatinem/rust-cache@v2
      - name: rustlings install
        run: cargo install rustlings
      - name: output check
        run: rustlings check-all
      - name: rustlings done check
        run: rustlings check-all | grep -q "You made it to the Fe-nish line\!"
