name: Check

on:
  pull_request:
    branches: [master]

jobs:
  dev-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install rustlings
        run: |
          cd rustlings_cli
          cargo install --path .
      - name: Run rustlings check-all in mininal set up
        run: rustlings-hse check-all -m
