name: Check

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  dev-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Run rustlings check-all without terminal size error
        run: rustlings check-all
        env:
          CARGO_TERM_COLOR: never
          COLUMNS: 80
          LINES: 24
